In [ ]:
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

file_id = '1y2Ily2WiJ7xQw3IT_zgR0efUgO7vtax3'
downloaded = drive.CreateFile({'id': file_id})
downloaded.GetContentFile('covid.csv')
!ls -lha covid.csv
!pip install -q xlrd

import pandas as pd
df = pd.read_csv('covid.csv')
df.head()

In [ ]:
import sklearn
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn import svm
from sklearn.neural_network import MLPClassifier 
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier
import xgboost as xgb
%matplotlib inline

In [ ]:
import numpy as np
from array import*
ds=df.iloc[:,:]
dm=df.iloc[:,19:23].values
severity=[]
for i in dm:
  a=i.tolist()
  if (a==[1,0,0,0]):
    severity.append(1)
  elif(a==[0,1,0,0]):
    severity.append(2)
  elif(a==[0,0,1,0]):
    severity.append(0)
  elif(a==[0,0,0,1]):
    severity.append(3)
  else:
    severity.append(np.nan)
ds=ds.assign(Severity=severity)

da=ds.iloc[:,11:16].values
age=[]
for i in da:
  a=list(i)
  if (a==[1, 0, 0, 0, 0]):
    age.append(0)
  elif (a==[0, 1, 0, 0, 0]):
    age.append(1)
  elif (a==[0, 0, 1, 0, 0]):
    age.append(2)
  elif (a==[0, 0, 0, 1, 0]):
     age.append(3)
  elif (a==[0, 0, 0, 0, 1]):
    age.append(4)
  else:
    age.append(np.nan)
ds=ds.assign(Age=age)

dp=ds.iloc[:,16:19].values
gender=[]
for i in dp:
  a=list(i)
  if (a==[1, 0, 0]):
    gender.append(2)
  elif (a==[0, 1, 0]):
    gender.append(1)
  elif (a==[0, 0, 1]):
    gender.append(0)
  else:
    gender.append(np.nan)
ds=ds.assign(Gender=gender)

dc=ds.iloc[:,23:26].values
contact=[]
for i in dc:
  a=list(i)
  if (a==[1, 0, 0]):
    contact.append(1)
  elif (a==[0, 1, 0]):
    contact.append(0)
  elif (a==[0, 0, 1]):
    contact.append(2)
  else:
    contact.append(np.nan)
ds=ds.assign(Contact=contact)

ds.drop(columns="Age_0-9",axis=1,inplace=True)
ds.drop(columns="Age_10-19",axis=1,inplace=True)
ds.drop(columns="Age_20-24",axis=1,inplace=True)
ds.drop(columns="Age_25-59",axis=1,inplace=True)
ds.drop(columns="Gender_Female",axis=1,inplace=True)
ds.drop(columns="Gender_Male",axis=1,inplace=True)
ds.drop(columns="Gender_Transgender",axis=1,inplace=True)
ds.drop(columns="Severity_Mild",axis=1,inplace=True)
ds.drop(columns="Severity_Moderate",axis=1,inplace=True)
ds.drop(columns="Severity_None",axis=1,inplace=True)
ds.drop(columns="Severity_Severe",axis=1,inplace=True)
ds.drop(columns="Contact_Dont-Know",axis=1,inplace=True)
ds.drop(columns="Contact_No",axis=1,inplace=True)
ds.drop(columns="Contact_Yes",axis=1,inplace=True)
ds.head()

   Fever  Tiredness  Dry-Cough  ...  Age  Gender  Contact
0      1          1          1  ...    0       1        2
1      1          1          1  ...    0       1        0
2      1          1          1  ...    0       1        1
3      1          1          1  ...    0       1        2
4      1          1          1  ...    0       1        0

[5 rows x 16 columns]

In [ ]:
y=df.iloc[:,13].values

In [ ]:
from sklearn.preprocessing import LabelEncoder
lc=LabelEncoder()
encod_country=df['Country'].values
encod_country=lc.fit_transform(encod_country)
encod_country

array([0, 0, 0, ..., 5, 5, 5])

In [ ]:
df.assign(Country_=encod_country)

        Fever  Tiredness  Dry-Cough  ...  Contact_Yes  Country  Country_
0           1          1          1  ...            1    China         0
1           1          1          1  ...            0    China         0
2           1          1          1  ...            0    China         0
3           1          1          1  ...            1    China         0
4           1          1          1  ...            0    China         0
...       ...        ...        ...  ...          ...      ...       ...
316795      0          0          0  ...            0    Other         5
316796      0          0          0  ...            0    Other         5
316797      0          0          0  ...            1    Other         5
316798      0          0          0  ...            0    Other         5
316799      0          0          0  ...            0    Other         5

[316800 rows x 28 columns]

In [ ]:
df.drop(columns="Country",axis=1,inplace=True)
df.head()

KeyError: ignored

In [ ]:
df.drop(columns="Severity",axis=1,inplace=True)

KeyError: ignored

In [ ]:
x=df.values

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
key = ['LogisticRegression','KNeighborsClassifier','SVC','DecisionTreeClassifier','RandomForestClassifier','GradientBoostingClassifier','AdaBoostClassifier','XGBClassifier']
value = [LogisticRegression(solver='lbfgs',max_iter=350000),KNeighborsClassifier(),SVC(kernel='rbf'),DecisionTreeClassifier(),RandomForestClassifier(),GradientBoostingClassifier(),AdaBoostClassifier(),xgb.XGBClassifier()]
models = dict(zip(key,value))

In [ ]:
for name,algo in models.items():
  model=algo
  model.fit(x_train,y_train)
  y_pred=model.predict(x_test)
  print(name)
  print(confusion_matrix(y_test,y_pred))
  print(accuracy_score(y_test,y_pred))

LogisticRegression
[[50787     0]
 [    0 12573]]
1.0
KNeighborsClassifier
[[50787     0]
 [    0 12573]]
1.0
SVC
[[50787     0]
 [    0 12573]]
1.0
DecisionTreeClassifier
[[50787     0]
 [    0 12573]]
1.0
RandomForestClassifier
[[50787     0]
 [    0 12573]]
1.0
GradientBoostingClassifier
[[50787     0]
 [    0 12573]]
1.0
AdaBoostClassifier
[[50787     0]
 [    0 12573]]
1.0
XGBClassifier
[[50787     0]
 [    0 12573]]
1.0